# Gilhari RESTful microservice: hana-poc-service
# Generated by orm_skyway.py
# Builds on the base Gilhari image (REST server pre-installed).
ARG BASE_PLATFORM=linux/amd64
FROM --platform=${BASE_PLATFORM} softwaretree/gilhari

WORKDIR /opt/hana-poc-service

# bin/ includes all .class files (top-level and inner classes)
# config/ includes .docker.jdx ORM spec, JDBC driver JAR, classnames_map.json
ADD bin ./bin
ADD config ./config
ADD gilhari_service.config .

EXPOSE 8081

CMD ["node", "/node/node_modules/gilhari_rest_server/gilhari_rest_server.js", "gilhari_service.config"]
