REM sampleCurlWriteCommands.cmd — Example write operations (POST, PUT, PATCH, DELETE) for this Gilhari service
REM Generated by orm_skyway.py
REM
REM All curl commands below are commented out (REM) to prevent accidental
REM execution. To use a command, remove the REM prefix on the curl line
REM and replace placeholder values with real ones.
REM Each command WILL modify data in your database.
REM For read-only (GET) operations, use sampleCurlCommands.cmd instead.
REM
SET BASE_URL=http://localhost:80/gilhari/v1

REM --- Categories ---

REM POST: Insert a new Categories object
REM curl -s -X POST %BASE_URL%/Categories -H "Content-Type: application/json" -d "{\"entity\": {\\\"ID\\\": 1, \\\"DESCRIPTION\\\": \\\"sample_value\\\", \\\"CREATED_AT\\\": \\\"2026-01-01T00:00:00\\\", \\\"CREATED_DATE\\\": \\\"2026-01-01\\\", \\\"SORT_ORDER\\\": 1, \\\"IS_ACTIVE\\\": true, \\\"NAME\\\": \\\"sample_value\\\"}}"

REM PUT: Update a specific Categories object (supply primary key + all attributes)
REM curl -s -X PUT %BASE_URL%/Categories/updateEntity -H "Content-Type: application/json" -d "{\"entity\": {\\\"ID\\\": 1, \\\"DESCRIPTION\\\": \\\"sample_value\\\", \\\"CREATED_AT\\\": \\\"2026-01-01T00:00:00\\\", \\\"CREATED_DATE\\\": \\\"2026-01-01\\\", \\\"SORT_ORDER\\\": 1, \\\"IS_ACTIVE\\\": true, \\\"NAME\\\": \\\"sample_value\\\"}}"

REM PATCH: Bulk-update Categories objects matching a filter (returns count of updated objects)
REM curl -s -X PATCH "%BASE_URL%/Categories?filter=ID=1" -H "Content-Type: application/json" -d "{\"newValues\": [\\\"DESCRIPTION\\\", \\\"sample_value\\\"]}"

REM DELETE: Delete Categories objects matching a filter
REM curl -s -X DELETE "%BASE_URL%/Categories?filter=ID=1"

REM --- Products ---

REM POST: Insert a new Products object
REM curl -s -X POST %BASE_URL%/Products -H "Content-Type: application/json" -d "{\"entity\": {\\\"STOCK_COUNT\\\": 1, \\\"PRICE\\\": 0.00, \\\"NOTES\\\": \\\"sample_value\\\", \\\"AVAILABLE_TIME\\\": \\\"value\\\", \\\"ID\\\": 1, \\\"IN_STOCK\\\": true, \\\"CATEGORY_ID\\\": 1, \\\"WEIGHT_KG\\\": 0.0, \\\"LAST_UPDATED\\\": \\\"2026-01-01T00:00:00\\\", \\\"SUPPLIER_ID\\\": 1, \\\"NAME\\\": \\\"sample_value\\\"}}"

REM PUT: Update a specific Products object (supply primary key + all attributes)
REM curl -s -X PUT %BASE_URL%/Products/updateEntity -H "Content-Type: application/json" -d "{\"entity\": {\\\"STOCK_COUNT\\\": 1, \\\"PRICE\\\": 0.00, \\\"NOTES\\\": \\\"sample_value\\\", \\\"AVAILABLE_TIME\\\": \\\"value\\\", \\\"ID\\\": 1, \\\"IN_STOCK\\\": true, \\\"CATEGORY_ID\\\": 1, \\\"WEIGHT_KG\\\": 0.0, \\\"LAST_UPDATED\\\": \\\"2026-01-01T00:00:00\\\", \\\"SUPPLIER_ID\\\": 1, \\\"NAME\\\": \\\"sample_value\\\"}}"

REM PATCH: Bulk-update Products objects matching a filter (returns count of updated objects)
REM curl -s -X PATCH "%BASE_URL%/Products?filter=ID=1" -H "Content-Type: application/json" -d "{\"newValues\": [\\\"STOCK_COUNT\\\", 1]}"

REM DELETE: Delete Products objects matching a filter
REM curl -s -X DELETE "%BASE_URL%/Products?filter=ID=1"

REM --- Suppliers ---

REM POST: Insert a new Suppliers object
REM curl -s -X POST %BASE_URL%/Suppliers -H "Content-Type: application/json" -d "{\"entity\": {\\\"ID\\\": 1, \\\"CREATED_AT\\\": \\\"2026-01-01T00:00:00\\\", \\\"RATING\\\": 0.0, \\\"CONTACT_EMAIL\\\": \\\"sample_value\\\", \\\"IS_ACTIVE\\\": true, \\\"NAME\\\": \\\"sample_value\\\"}}"

REM PUT: Update a specific Suppliers object (supply primary key + all attributes)
REM curl -s -X PUT %BASE_URL%/Suppliers/updateEntity -H "Content-Type: application/json" -d "{\"entity\": {\\\"ID\\\": 1, \\\"CREATED_AT\\\": \\\"2026-01-01T00:00:00\\\", \\\"RATING\\\": 0.0, \\\"CONTACT_EMAIL\\\": \\\"sample_value\\\", \\\"IS_ACTIVE\\\": true, \\\"NAME\\\": \\\"sample_value\\\"}}"

REM PATCH: Bulk-update Suppliers objects matching a filter (returns count of updated objects)
REM curl -s -X PATCH "%BASE_URL%/Suppliers?filter=ID=1" -H "Content-Type: application/json" -d "{\"newValues\": [\\\"CREATED_AT\\\", \\\"2026-01-01T00:00:00\\\"]}"

REM DELETE: Delete Suppliers objects matching a filter
REM curl -s -X DELETE "%BASE_URL%/Suppliers?filter=ID=1"

