REM sampleCurlWriteCommands.cmd -- Example write operations (POST, PUT, PATCH, DELETE) for this Gilhari service
REM Generated by orm_skyway.py
REM
REM All curl commands below are uncommented to allow direct execution.
REM Each command WILL modify data in your database.
REM For read-only (GET) operations, use sampleCurlCommands.cmd instead.
REM
SET BASE_URL=http://localhost:80/gilhari/v1

echo Starting write operations > curlWrite.log

REM --- Categories ---

REM POST: Insert a new Categories object
echo POST Categories >> curlWrite.log
curl.exe -s -X POST %BASE_URL%/Categories -H "Content-Type: application/json" -d "{\"entity\": {\"ID\": 101, \"DESCRIPTION\": \"Electronics Accessories\", \"CREATED_AT\": \"2026-07-17T10:00:00\", \"CREATED_DATE\": \"2026-07-17\", \"SORT_ORDER\": 1, \"IS_ACTIVE\": true, \"NAME\": \"Cables\"}}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM PUT: Update a specific Categories object (supply primary key + all attributes)
echo PUT Categories >> curlWrite.log
curl.exe -s -X PUT %BASE_URL%/Categories/updateEntity -H "Content-Type: application/json" -d "{\"entity\": {\"ID\": 101, \"DESCRIPTION\": \"Updated Electronics Accessories\", \"CREATED_AT\": \"2026-07-17T10:00:00\", \"CREATED_DATE\": \"2026-07-17\", \"SORT_ORDER\": 2, \"IS_ACTIVE\": true, \"NAME\": \"Premium Cables\"}}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM PATCH: Bulk-update Categories objects matching a filter (returns count of updated objects)
echo PATCH Categories >> curlWrite.log
curl.exe -s -X PATCH "%BASE_URL%/Categories?filter=ID=101" -H "Content-Type: application/json" -d "{\"newValues\": [\"DESCRIPTION\", \"Patched Accessories\"]}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM --- Suppliers ---

REM POST: Insert a new Suppliers object
echo POST Suppliers >> curlWrite.log
curl.exe -s -X POST %BASE_URL%/Suppliers -H "Content-Type: application/json" -d "{\"entity\": {\"ID\": 101, \"CREATED_AT\": \"2026-07-17T10:00:00\", \"RATING\": 4.5, \"CONTACT_EMAIL\": \"contact@techsupply.com\", \"IS_ACTIVE\": true, \"NAME\": \"TechSupply Inc\"}}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM PUT: Update a specific Suppliers object (supply primary key + all attributes)
echo PUT Suppliers >> curlWrite.log
curl.exe -s -X PUT %BASE_URL%/Suppliers/updateEntity -H "Content-Type: application/json" -d "{\"entity\": {\"ID\": 101, \"CREATED_AT\": \"2026-07-17T10:00:00\", \"RATING\": 4.8, \"CONTACT_EMAIL\": \"info@techsupply.com\", \"IS_ACTIVE\": true, \"NAME\": \"TechSupply Global\"}}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM PATCH: Bulk-update Suppliers objects matching a filter (returns count of updated objects)
echo PATCH Suppliers >> curlWrite.log
curl.exe -s -X PATCH "%BASE_URL%/Suppliers?filter=ID=101" -H "Content-Type: application/json" -d "{\"newValues\": [\"RATING\", 5.0]}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM --- Products ---

REM POST: Insert a new Products object
echo POST Products >> curlWrite.log
curl.exe -s -X POST %BASE_URL%/Products -H "Content-Type: application/json" -d "{\"entity\": {\"STOCK_COUNT\": 50, \"PRICE\": 15.99, \"NOTES\": \"High quality HDMI cable\", \"AVAILABLE_TIME\": \"12:00:00\", \"ID\": 101, \"IN_STOCK\": true, \"CATEGORY_ID\": 101, \"WEIGHT_KG\": 0.2, \"LAST_UPDATED\": \"2026-07-17T10:00:00\", \"SUPPLIER_ID\": 101, \"NAME\": \"HDMI Cable\"}}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM PUT: Update a specific Products object (supply primary key + all attributes)
echo PUT Products >> curlWrite.log
curl.exe -s -X PUT %BASE_URL%/Products/updateEntity -H "Content-Type: application/json" -d "{\"entity\": {\"STOCK_COUNT\": 40, \"PRICE\": 14.99, \"NOTES\": \"Discounted HDMI cable\", \"AVAILABLE_TIME\": \"12:00:00\", \"ID\": 101, \"IN_STOCK\": true, \"CATEGORY_ID\": 101, \"WEIGHT_KG\": 0.2, \"LAST_UPDATED\": \"2026-07-17T11:00:00\", \"SUPPLIER_ID\": 101, \"NAME\": \"HDMI Cable 2.0\"}}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM PATCH: Bulk-update Products objects matching a filter (returns count of updated objects)
echo PATCH Products >> curlWrite.log
curl.exe -s -X PATCH "%BASE_URL%/Products?filter=ID=101" -H "Content-Type: application/json" -d "{\"newValues\": [\"STOCK_COUNT\", 35]}" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM --- CLEANUP (Deletes) ---
REM Note: Products must be deleted before Categories/Suppliers due to foreign keys.

REM DELETE: Delete Products objects matching a filter
echo DELETE Products >> curlWrite.log
curl.exe -s -X DELETE "%BASE_URL%/Products?filter=ID=101" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM DELETE: Delete Suppliers objects matching a filter
echo DELETE Suppliers >> curlWrite.log
curl.exe -s -X DELETE "%BASE_URL%/Suppliers?filter=ID=101" >> curlWrite.log 2>&1
echo. >> curlWrite.log

REM DELETE: Delete Categories objects matching a filter
echo DELETE Categories >> curlWrite.log
curl.exe -s -X DELETE "%BASE_URL%/Categories?filter=ID=101" >> curlWrite.log 2>&1
echo. >> curlWrite.log

echo Finished write operations >> curlWrite.log
