#!/bin/bash
# Sample curl commands for the Gilhari microservice.
# Generated by orm_skyway.py
#
# GET commands use deep=true (includes related objects) and maxObjects=5.
# Use deep=false to exclude related objects (useful for complex object graphs).
# Remove maxObjects to retrieve all qualifying objects,
# or change it to a different value (-1 to get all qualifying objects).
#
# Responses are recorded in curl.log.
#
# You may optionally specify a port as the first argument:
#   ./sampleCurlCommands.sh 8899
port="${1:-80}"

# Truncate curl.log at the start so it does not grow across runs
> curl.log

echo "** BEGIN OUTPUT **" >> curl.log
echo "" >> curl.log

# -- Health check --
echo "** Health check" >> curl.log
curl -s "http://localhost:$port/gilhari/v1/health/check" | python3 -m json.tool >> curl.log
echo "" >> curl.log

# -- Object model summary (plain text response, not JSON) --
echo "** Object model summary" >> curl.log
curl -s "http://localhost:$port/gilhari/v1/getObjectModelSummary/now" >> curl.log
echo "" >> curl.log

# -- GET Categories objects - deep (includes related objects, up to 5) --
echo "** GET Categories objects (deep)" >> curl.log
curl -s -X GET "http://localhost:$port/gilhari/v1/Categories?deep=true&maxObjects=5" -H "Content-Type: application/json" | python3 -m json.tool >> curl.log
echo "" >> curl.log

# -- GET Categories objects - shallow (excludes related objects, up to 5) --
echo "** GET Categories objects (shallow)" >> curl.log
curl -s -X GET "http://localhost:$port/gilhari/v1/Categories?deep=false&maxObjects=5" -H "Content-Type: application/json" | python3 -m json.tool >> curl.log
echo "" >> curl.log

# -- GET Products objects - deep (includes related objects, up to 5) --
echo "** GET Products objects (deep)" >> curl.log
curl -s -X GET "http://localhost:$port/gilhari/v1/Products?deep=true&maxObjects=5" -H "Content-Type: application/json" | python3 -m json.tool >> curl.log
echo "" >> curl.log

# -- GET Products objects - shallow (excludes related objects, up to 5) --
echo "** GET Products objects (shallow)" >> curl.log
curl -s -X GET "http://localhost:$port/gilhari/v1/Products?deep=false&maxObjects=5" -H "Content-Type: application/json" | python3 -m json.tool >> curl.log
echo "" >> curl.log

echo "** END OUTPUT **" >> curl.log
echo "" >> curl.log
cat curl.log
